theme: minima
title: chidozinyakatira
descripition: This is my GitHub Pages site
title: This is my  research project Site
description: Welcome to my Time Series Analysis Research Project
Author: Chido S Zinyakatira
